package com.sayem.chainsupershopmanagement.model;
// Generated Mar 1, 2020 11:45:56 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Purchase generated by hbm2java
 */
@Entity
public class Purchase  implements java.io.Serializable {


     private Integer purid;
     private Date purdate;
     private String emailid;

    public Purchase() {
    }

    public Purchase(Date purdate, String emailid) {
       this.purdate = purdate;
       this.emailid = emailid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="purid", unique=true, nullable=false)
    public Integer getPurid() {
        return this.purid;
    }
    
    public void setPurid(Integer purid) {
        this.purid = purid;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="purdate", nullable=false, length=10)
    public Date getPurdate() {
        return this.purdate;
    }
    
    public void setPurdate(Date purdate) {
        this.purdate = purdate;
    }
 
    @Column(name="emailid", nullable=false, length=45)
    public String getEmailid() {
        return this.emailid;
    }
    
    public void setEmailid(String emailid) {
        this.emailid = emailid;
    }




}


